language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # install meteor
  - psql -c "CREATE DATABASE;"
  - psql -c "CREATE USER tester WITH PASSWORD 'test';"
  - psql -c "create database test;"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE 'test' to tester;"
  - npm install -g nightwatch
script: npm test