node_js:
  - "node"
sudo: required  
dist: trusty  
language: node_js
services:
  - postgresql
before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0 
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # install meteor
  - psql -c "CREATE USER tester WITH PASSWORD 'test';" -U postgres
  - psql -c "create database test;"  -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test to tester;" -U postgres
  - npm install -g nightwatch
script: npm test